import 'core-js/features/object/entries'
import { Task } from './types'
export type Task = Task
export { addTask, delTasks } from './helpers'
export { default as taskReducer } from './reducer'
export { default as Agent } from './Agent'
export { default as http } from './HttpTask'
export { default as time } from './TimeTask'
export { default as rng } from './RNGTask'
export { default as websocket } from './WebSocketTask'
export { default as storage } from './LocalStorageTask'
